name: field_suggestion
description: This package helps to make beautiful type ahead fields. It listens values of given TextEditingController and checks if the given value is in the given suggestion list or not. 
version: 0.1.0
homepage: https://github.com/theiskaa/field_suggestion
issue_tracker: https://github.com/theiskaa/field_suggestion/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
